name: Quinto Workflow

on:
  push:
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Exibir data
        run: date
      
      - name: Exibir versão do git
        run: git --version

  segundo-job:
    needs: primeiro-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Verificar README.md
        run: test -f README.md
      
      - name: Verificar License
        run: test -f LICENSE
    
      - name: Verificar .gitignore
        run: test -f .gitignore

    
    